import { useAtom } from 'jotai';
import React, { useState } from 'react';
import { Locale } from 'antd/lib/locale';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "THE CKB",
  description: "Generated by create next app",
  keywords:'',
};

function Header({ title }:{title?: string}) {
  return <h1>{title ? title : 'Default title'}</h1>;
}


export default function HomePage() {
  return (
    <>
      22222
      </>
  );
}

